steps:
- name: 'gcr.io/$PROJECT_ID/go-mod-ginkgo:0.2.1'
  id: 'resolve-dependencies'
  entrypoint: 'sh'
  args: ['-c', 'make resolve-deps']
  volumes: &vol
  - name: go-modules
    path: /go

- name: 'gcr.io/$PROJECT_ID/go-mod-ginkgo:0.2.1'
  id: 'build-plugins-for-tests'
  entrypoint: 'sh'
  args: ['-c', 'make build-plugins-for-tests']
  volumes: *vol

- name: 'gcr.io/$PROJECT_ID/go-mod-ginkgo:0.2.1'
  id: 'test-plugins'
  args: ['-r', 'plugins']
  env:
  - 'GOPATH=/go'
  volumes: *vol

- name: 'gcr.io/$PROJECT_ID/go-mod-ginkgo:0.2.1'
  id: 'build'
  entrypoint: 'sh'
  args: ['-c', 'make build']
  volumes: *vol